name: user_repository
description: User repository
version: 0.0.1
homepage: https://github.com/esgi-lyon/flutter-abcleaver
publish_to: none

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  equatable: ^2.0.0
  uuid: ^3.0.0
  authserver:
    path: ../authserverapi
  dio: '>=4.0.6 <5.0.0'
  pretty_dio_logger: ^1.2.0-beta-1

dev_dependencies: {}
