name: Build and run tests

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'

jobs:
  test:
    strategy:
      matrix:
        java: [17]
        os: [ubuntu-latest]
    name: Tests - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: develop
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: 'gradle'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: '2.6.1'

      - run: pnpm nx affected --target=format-check --parallel=3
      - run: pnpm nx affected --target=test --parallel=3
        env:
          INTEGRATION_TEST_BOOT_TIME_MULTIPLIER: 2

      - uses: actions/upload-artifact@v3
        with:
          name: integration-report
          path: file:///home/runner/work/monorepo/monorepo/apps/integrationtesting/build/reports/tests/test/index.html
          if-no-files-found: warn

      - run: pnpm nx affected --target=build --parallel=3
