name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy images to registery
    if: >
      contains(github.event.head_commit.message, '[skip-release]') == false
      && contains(github.event.pull_request.labels.*.name, 'skip-release') == false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v2
        if: github.ref == 'refs/heads/develop'
        with:
          main-branch-name: develop

      - uses: nrwl/nx-set-shas@v2
        if: github.ref == 'refs/heads/main'
        with:
          main-branch-name: main

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Login to Github Registery
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: semver plugins (main)
        run: |
          pnpm nx affected --head=HEAD --target buildImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
