name: Pr check

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  test:
    name: Pr title check
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: false
