name: Bump version and release

on:
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  artifact:
    name: Publish - GitHub Packages
    if: >
      contains(github.event.head_commit.message, '[skip-release]') == false
      && contains(github.event.pull_request.labels.*.name, 'skip-release') == false

    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: log commit in common
        run: |
          git fetch --all;
          [[ -z $(git branch -a --list origin/develop) ]] && exit 0;
          [[ $(git rev-parse --verify HEAD) = $(git rev-parse --verify origin/develop) ]] \
           && echo 'History OK' && exit 0 || echo "history don't match with pre-release" && exit 1;

      - uses: nrwl/nx-set-shas@v2
        if: github.ref == 'refs/heads/develop'
        with:
          main-branch-name: develop

      - uses: nrwl/nx-set-shas@v2
        if: github.ref == 'refs/heads/main'
        with:
          main-branch-name: main

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Setup github bot
        env:
          BOT_USER: ${{ github.actor }}
        run: |
          git config --global user.email "$BOT_USER@users.noreply.github.com"
          git config --global user.name "Github actions"

      - name: semver plugins (develop)
        shell: bash
        run: |
          pnpm nx affected --head=HEAD --base=develop~1 --target version -- --releaseAs=prerelease --preid=beta
        if: github.ref == 'refs/heads/develop'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: semver plugins (main)
        run: |
          pnpm nx affected --head=HEAD --base=main~1 --target version
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
