name: authentication_repository
description: authentication repository
version: 0.0.1
homepage: https://github.com/esgi-lyon/flutter-abcleaver
publish_to: none

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: '>=1.17.0'
dependencies:
  equatable: ^2.0.3
  ffi: ^2.0.1
  local_auth: ^2.1.0
  authserver:
    path: ../authserverapi
  dio: '>=4.0.6 <5.0.0'
  json_annotation: ^4.6.0
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0
  pretty_dio_logger: ^1.2.0-beta-1

dev_dependencies:
  json_serializable: '^6.1.5'
