version: '3.9'
services:

  auth-server:
    image: docker.io/loicroux/auth-server:develop
    networks:
      - internals
    ports:
      - "3333:3333"
    environment:
      - PG_HOST=postgres
    depends_on:
      postgres:
        condition: service_started

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      # Standard port for PostgreSQL databases
      - "5432:5432"
    volumes:
      - pgsql:/var/lib/postgresql/data
      - ./ops/db-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql:rw
    networks:
      - internals

networks:
  internals: {}

volumes:
  pgsql:
