openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8085
    description: Generated server url
paths:
  /:
    get:
      tags:
        - main-controller
      operationId: index
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
components: {}
