// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2W0xv_sqx9R6hemSc66HnruTqHvNg5yU',
    appId: '1:768906734565:web:893ee735a244eb6a36dd0c',
    messagingSenderId: '768906734565',
    projectId: 'abcleaver-auth',
    authDomain: 'abcleaver-auth.firebaseapp.com',
    storageBucket: 'abcleaver-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4KasnUE6op3IqqbPUxVQDPks6qqpaLF4',
    appId: '1:768906734565:android:d769fa46f05f746b36dd0c',
    messagingSenderId: '768906734565',
    projectId: 'abcleaver-auth',
    storageBucket: 'abcleaver-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfgYL3-0qDjIWaEmmddVolVZJB-C3EkLA',
    appId: '1:768906734565:ios:0b4fdaf251ec54e936dd0c',
    messagingSenderId: '768906734565',
    projectId: 'abcleaver-auth',
    storageBucket: 'abcleaver-auth.appspot.com',
    iosClientId: '768906734565-os1d00okm4ucqlmg5htsmgic2uch05kc.apps.googleusercontent.com',
    iosBundleId: 'com.example.abcleaverfront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfgYL3-0qDjIWaEmmddVolVZJB-C3EkLA',
    appId: '1:768906734565:ios:0b4fdaf251ec54e936dd0c',
    messagingSenderId: '768906734565',
    projectId: 'abcleaver-auth',
    storageBucket: 'abcleaver-auth.appspot.com',
    iosClientId: '768906734565-os1d00okm4ucqlmg5htsmgic2uch05kc.apps.googleusercontent.com',
    iosBundleId: 'com.example.abcleaverfront',
  );
}
